ex3/ex3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    # path('', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ex3/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),

    path('register/', views.UserFormView.as_view(), name='register'),

    # /music/<album_id>/
    path('<pk>/', views.DetailView.as_view(), name='detail'),

    # music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # music/album/2/
    path('album/<pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    # music/album/2/delete
    path('album/<pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
]

ex3/music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# Red pk 1
class Album(models.Model):
    artist = models.CharField(max_length = 250)
    album_title = models.CharField(max_length = 500)
    genre = models.CharField(max_length = 100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length = 10)
    song_title = models.CharField(max_length = 250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

ex3/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

ex3/music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Album
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(serl):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form':form})

ex3/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a New Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 com-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'music/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Summit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

ex3/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine" type="text/css"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">

        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items  -->
        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="{% url 'music:index' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Album
              </a>
            </li>
            <li>
              <a href="#">
                <sapn class="glyphicon glyphicon-music" aria-hidden="true"></sapn>&nbsp; Songs
              </a>
            </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" name="q" id="" class="form-control">
            </div>
              <button type="submit" class="btn btn-default">Search</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'music:album-add' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Album</a></li>
            <li><a href=""><span class="glyphicon glyphicon-off" aria-hidden="true"></span>Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
  </body>
</html>

ex3/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Detail {% endblock %}

{% block body %}
  <img src="{{album.album_logo.url}}" >
  <h1> {{album.album_title}}</h1>
  <h3> {{ album.artist }}</h3>

    {% csrf_token %}
    {% for song in album.song_set.all %}
        {{song.song_title}}
        {% if song.is_favorite %}
          <img src="https://i.imgur.com/b9b13Rd.png">
        {% endif %}
      <br>
    {% endfor %}

{% endblock %}

ex3/music/templates/music/detail_old.html
<img src="{{album.album_logo}}" >
<h1> {{album.album_title}}</h1>
<h3> {{ album.artist }}</h3>

<ul>
  {% for song in album.song_set.all %}
  <li> {{ song.song_title }} - {{ song.file_type }} </li>
  {% endfor %}
</ul>

ex3/music/templates/music/detail_~ch28.html
{% extends 'music/base.html' %}
{% block title %} Album Detail {% endblock %}

{% block body %}
  <img src="{{album.album_logo}}" >
  <h1> {{album.album_title}}</h1>
  <h3> {{ album.artist }}</h3>

  {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
  {% endif %}


  <form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
      <label for="song{{forloop.counter}}">
        {{song.song_title}}
        {% if song.is_favorite %}
          <img src="https://i.imgur.com/b9b13Rd.png">
        {% endif %}
      </label><br>
    {% endfor %}
  <input type="submit" value="Favorite">
  </form>
{% endblock %}

ex3/music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.error}}</span>
    </div>
    <label for="" class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
  </div>
{% endfor %}

ex3/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if object_list %}
            {% for album in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}

ex3/music/templates/music/index_old.html
{% if all_albums %}
  <h3>Here are all my albums:</h3>
  <ul>
    {% for album in all_albums %}
    <li><a href="/music/{{ album.id }}/">{{album.album_title}}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <h3>You don't have any albums</h3>
{% endif %}

ex3/music/templates/music/index_ref.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'music:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}

ex3/music/templates/music/index_~29.html
{% extends 'music/base.html' %}

{% block body %}

  <ul>
    {% for album in object_list %}
    <li><a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
    {% endfor %}
  </ul>

{% endblock %}

ex3/music/templates/music/index_~ch28.html
{% extends 'music/base.html' %}


{% block body %}

  {% if all_albums %}
      <h3>Here are all my albums:</h3>
      <ul>
        {% for album in object_list %}
        <li><a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
        {% endfor %}
      </ul>
    {% else %}
      <h3>You don't have any albums</h3>
  {% endif %}

{% endblock %}

ex3/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} register {% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 com-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3> Create a New Account</h3>
          {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'music/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Summit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}